language: node_js

node_js:
  - "4.1"
  - "6"

sudo: false

git:
  depth: 1

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:ocftw/civictechfest.org"
    - secure: "FC+k6by5XgeKD9tKMN4oEfDKkew4qNbGDVoFXnta3gTFRBUKNIcvtVgQ05GReM1v0LqQ75g1yy21IFmpBfj2Rg1LFBFHYKTOLOfwkEdNieqJh+ShNHhi1+md07HVmUASp8a02PeDcphrQnFjJyEbUhFe/lzSHYDf5Lj5BS4bEGNoa6TWYm+v/S5jkpiDoJMl5Gr49PWA48M5uiIXSJw2O6uJU4zk/eRNqsS26jYQC6tRjbOZ/wWSl1eSkH6bmpOIytKXzokrTZTlPnnH4IdxxMvx+Xrgv/3YBdRlv4FMifUnyECdkyHdWA3wgR5FNWEMcbWMMtTi/8UX6F6uwDlhT1RpUWrh/0GUhOk/yd3FrMaR/pKXhFGqSgJYACL1aSfe9RqKZSpJWhJe0ZyEvTQpgJGeCp1qsL/2RPbD+PuYXZLGSXj/bBp05KdDsTAkuuK6d3dG2oA62YyG/QwTrXTIHI2llwBk/LtzkPKc6NQ7d3GkcgYRNChRSDSYE5KLUa4wG70yqQN3F22QqVcor88wzvrQzVIahXhysuXrWF9xRMxSCutFJB0BUxU9V00hgLQI0hk2U+fu+FnE0rtxLUbABwxtTvoOUl6a9kPsABf9EHlVYi3TUzffouxbU6r6KJf0nc/qLc3KEJaHQWMcTOrgc7ISeFEqZWAWx45zSLE1HEQ="

after_success: .travis/after_success.sh
